apiVersion: v1
kind: Service
metadata:
  name: ps-nodeport
spec:
  type: NodePort
  ports:
  - port: 80 #service
    targetPort: 8080 #container
    nodePort: 31111 #node
    protocol: TCP
  selector:
    app: web
    